### ISSUE TITLE
QoE Figure plot

### ISSUE THREAD

**Issue by lesleychou** [linnaeushuang/pensieve-pytorch#1]
Hi author,

Thanks for your great work on pensieve with torch! It trained well and was very helpful to me!
I am wondering how did you plot the two QoE figure? Is there any code or platform you used?

Thanks,
Lesley

**Comment by linnaeushuang** [comment]
Hi, Sorry for a delayed response.I have uploaded a plot file, you can find it at `/img/plot.py`

**Comment by lesleychou** [comment]
wow thank you so much for the update!
This is super awesome:)
