### ISSUE TITLE
Should the initial state initialization be set without the outer array?

### ISSUE THREAD

**Issue by kasimte** [linnaeushuang/pensieve-pytorch#7]
Here, 

https://github.com/linnaeushuang/pensieve-pytorch/blob/e9b8aeb0fbed9f41e31b7e0c514e60f0a0f7bcf5/pensieve_torch.py#L231

, should the initial state be set like this without the wrapping array?

```
state = torch.zeros((1,S_INFO, S_LEN))
```

Thanks.

**Comment by linnaeushuang** [comment]
well,this code should not be wrapped by array.
https://github.com/linnaeushuang/pensieve-pytorch/blob/e9b8aeb0fbed9f41e31b7e0c514e60f0a0f7bcf5/pensieve_torch.py#L230

**Comment by linnaeushuang** [comment]
https://github.com/hongzimao/pensieve/blob/1120bb173958dc9bc9f2ebff1a8fe688b6f4e93c/sim/multi_agent.py#L270-272

**Comment by linnaeushuang** [comment]
well, this code should not be wrapped by array.
I wrote this code in reference to `hongzimao/pensieve/sim/multi_agent.py` ,line271.
I guess this code might have been used to handle some situations in older version. But in MAO's final version, this code would never be run.

**Comment by kasimte** [comment]
Thanks for commenting. I noticed that line in Mao's code too, and it seemed like a bug. I was just curious about your opinion.
